import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./Footer";  // Import the Footer component
import { Lexend_Deca } from "next/font/google"

const lexenddeca = Lexend_Deca({ subsets: ['latin']});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Team. ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${lexenddeca.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer /> {/* Include the Footer component */}
      </body>
    </html>
  );
}
